services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Sypets\Brofix\:
    resource: '../Classes/*'

  Sypets\Brofix\LinkAnalyzer:
    public: true

  Sypets\Brofix\Repository\BrokenLinkRepository:
    public: true

  # EventListeners
  Sypets\Brofix\EventListener\CheckBrokenRteLinkEventListener:
    tags:
      - name: event.listener
        identifier: 'rte-check-link-external'
        event: TYPO3\CMS\Core\Html\Event\BrokenLinkAnalysisEvent
        method: 'checkExternalLink'
      - name: event.listener
        identifier: 'rte-check-link-to-page'
        event: TYPO3\CMS\Core\Html\Event\BrokenLinkAnalysisEvent
        method: 'checkPageLink'
      - name: event.listener
        identifier: 'rte-check-link-to-file'
        event: TYPO3\CMS\Core\Html\Event\BrokenLinkAnalysisEvent
        method: 'checkFileLink'

  # Cache
  cache.brofix_checklinkcache:
    class: TYPO3\CMS\Core\Cache\Frontend\FrontentInterface
    factory: ['@TYPO3\CMS\Core\Cache\CacheManager', 'getCache']
    arguments: ['brofix_checklinkcache']

  # Commands
  Sypets\Brofix\Command\CheckLinksCommand:
    tags:
      - name: 'console.command'
        command: 'brofix:checklinks'
        description: 'Check for broken links'
        hidden: false
  Sypets\Brofix\Command\CheckLinksIncrementalCommand:
    tags:
      - name: 'console.command'
        command: 'brofix:checklinksInc'
        description: 'Check for broken links (incremental)'
        hidden: false
